version: "3"

services:
  hello-docker:
    image: hello-docker
    build: .
    ports:
      - "3000:3000"
    container_name: hello-container
    volumes:
      - ./:/app:ro
      - /app/node_modules

    environment:
      - PORT=3000
    # env_file:
    #   - ./.env
    