version: "3"

services:
  hello-docker:
    container_name: hello-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV : development
    volumes:
      - ./:/app:ro
      - /app/node_modules

    environment:
      - NODE_ENV=development
    command: npm run dev