version: "3"

services:
  node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV : development
    volumes:
      - ./:/app:ro
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - MONGO_USER=shubham
      - MONGO_PASSWORD=mypassword
    command: npm run dev

  mongo:
    environment:
        MONGO_INITDB_ROOT_USERNAME: shubham
        MONGO_INITDB_ROOT_PASSWORD: mypassword
       